spring:
  application:
    name: eureka-server
    profiles: peer2
server:
  port: 9000
eureka:
  instance:
    hostname: peer2
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://peer1:9000/eureka/,http://peer3:9000/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
    use-read-only-response-cache: false